dataset_names: ['Cora', 'Citeseer', 'Pubmed', 'CoauthorCS', 'Computers', 'Photo']
diff_methods: ['none', 'heat', 'ppr']


GCN:
    none:
        Cora:
            weight_decay: 0.06
            depth: 1
        
        Citeseer:
            weight_decay: 10.0
            depth: 1
        
        Pubmed:
            weight_decay: 0.03
            depth: 1
        
        CoauthorCS:
            weight_decay: 0.06
            depth: 1
        
        Computers:
            weight_decay: 0.03
            depth: 1
        
        Photo:
            weight_decay: 0.03
            depth: 1
    
    
    heat:
        Cora:
            t: 5
            k: 
            eps: 0.0001
            weight_decay: 0.09
            depth: 1
        
        Citeseer:
            t: 4
            k: 
            eps: 0.0009
            weight_decay: 10.0
            depth: 1
        
        Pubmed:
            t: 3
            k: 
            eps: 0.0001
            weight_decay: 0.04
            depth: 1
        
        CoauthorCS:
            t: 1
            k: 64
            eps: 
            weight_decay: 0.08
            depth: 1
        
        Computers:
            t: 5
            k: 
            eps: 0.0010
            weight_decay: 0.07
            depth: 1
        
        Photo:
            t: 3
            k: 
            eps: 0.0001
            weight_decay: 0.08
            depth: 2
    
    ppr:
        Cora:
            alpha: 0.05
            k: 128
            eps: 
            weight_decay: 0.10
            depth: 1
        
        Citeseer:
            alpha: 0.10
            k: 
            eps: 0.0009
            weight_decay: 10.0
            depth: 1
        
        Pubmed:
            alpha: 0.05
            k: 64
            eps: 
            weight_decay: 0.06
            depth: 1
        
        CoauthorCS:
            alpha: 0.05
            k: 64
            eps: 
            weight_decay: 0.03
            depth: 1
        
        Computers:
            alpha: 0.05
            k: 64
            eps: 
            weight_decay: 0.04
            depth: 1
        
        Photo:
            alpha: 0.05
            k: 64
            eps: 
            weight_decay: 0.03
            depth: 1

            
            

GAT:
    none:
        Cora:
            weight_decay: 0.06
            depth: 1
        
        Citeseer:
            weight_decay: 0.06
            depth: 1
        
        Pubmed:
            weight_decay: 0.03
            depth: 2
        
        CoauthorCS:
            weight_decay: 0.00
            depth: 2
        
        Computers:
            weight_decay: 0.09
            depth: 1
        
        Photo:
            weight_decay: 0.08
            depth: 1
    
    
    heat:
        Cora:
            t: 1
            k: 
            eps: 0.0010
            weight_decay: 0.04
            depth: 1
        
        Citeseer:
            t: 1
            k: 
            eps: 0.0010
            weight_decay: 0.08
            depth: 1
        
        Pubmed:
            t: 1
            k: 
            eps: 0.0005
            weight_decay: 0.02
            depth: 2
        
        CoauthorCS:
            t: 1
            k: 
            eps: 0.0005
            weight_decay: 0.03
            depth: 1
        
        Computers:
            t: 1
            k: 
            eps: 0.0005
            weight_decay: 0.01
            depth: 1
        
        Photo:
            t: 1
            k: 
            eps: 0.0005
            weight_decay: 0.01
            depth: 1
    
    ppr:
        Cora:
            alpha: 0.10
            k: 
            eps: 0.0050
            weight_decay: 0.10
            depth: 1
        
        Citeseer:
            alpha: 0.10
            k: 
            eps: 0.0005
            weight_decay: 10.0
            depth: 1
        
        Pubmed:
            alpha: 0.10
            k: 
            eps: 0.0005
            weight_decay: 0.06
            depth: 1
        
        CoauthorCS:
            alpha: 0.10
            k: 
            eps: 0.0005
            weight_decay: 0.03
            depth: 1
        
        Computers:
            alpha: 0.10
            k: 
            eps: 0.0005
            weight_decay: 0.04
            depth: 1
        
        Photo:
            alpha: 0.10
            k: 
            eps: 0.0005
            weight_decay: 0.03
            depth: 1

            